import { Text } from '@chakra-ui/react';
import Head from 'next/head';
import ContentCard from '../component/ContentCard';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>home page</h1>
    </div>
  );
}
